name: Update AUR Package

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allow manual triggering
  push:
    branches:
      - github
    paths-ignore:
      - '.github/**'  # Avoid recursion

jobs:
  update-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: github  # Explicitly checkout the github branch

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq build-essential

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Deploy SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.AUR_KNOWN_HOSTS }}
          if_key_exists: replace

      - name: Configure Git
        run: |
          git config --global user.name "${{ vars.AUR_USERNAME }}"
          git config --global user.email "${{ vars.AUR_EMAIL }}"

      - name: Check for updates
        id: check-updates
        run: |
          # Get current version from PKGBUILD
          CURRENT_VERSION=$(grep -oP '^pkgver=\K.*' PKGBUILD)
          
          # Get latest version from GitHub API
          LATEST_VERSION=$(curl -s "https://api.github.com/repos/Nerimity/nerimity-desktop/releases/latest" | jq -r .tag_name | sed 's/^v//g')
          
          echo "Current version: $CURRENT_VERSION"
          echo "Latest version: $LATEST_VERSION"
          
          if [ "$CURRENT_VERSION" != "$LATEST_VERSION" ]; then
            echo "update_needed=true" >> $GITHUB_OUTPUT
            echo "latest_version=$LATEST_VERSION" >> $GITHUB_OUTPUT
          else
            echo "update_needed=false" >> $GITHUB_OUTPUT
          fi

      - name: Update package in github branch
        if: steps.check-updates.outputs.update_needed == 'true'
        run: |
          # Update PKGBUILD
          sed -i "s/^pkgver=.*/pkgver=${{ steps.check-updates.outputs.latest_version }}/" PKGBUILD
          sed -i "s/^pkgrel=.*/pkgrel=1/" PKGBUILD
          
          # Install makepkg-template for generating .SRCINFO
          curl -o /tmp/makepkg-template.tar.gz https://aur.archlinux.org/cgit/aur.git/snapshot/makepkg-template.tar.gz
          tar -xf /tmp/makepkg-template.tar.gz -C /tmp
          
          # Generate .SRCINFO using a simple parser
          echo "pkgbase = nerimity-appimage" > .SRCINFO
          echo "	pkgdesc = $(grep -oP '^pkgdesc="\K[^"]+' PKGBUILD)" >> .SRCINFO
          echo "	pkgver = ${{ steps.check-updates.outputs.latest_version }}" >> .SRCINFO
          echo "	pkgrel = 1" >> .SRCINFO
          echo "	url = $(grep -oP '^url="\K[^"]+' PKGBUILD)" >> .SRCINFO
          echo "	install = nerimity-appimage.install" >> .SRCINFO
          echo "	arch = x86_64" >> .SRCINFO
          echo "	license = custom:unknown" >> .SRCINFO
          echo "	makedepends = curl" >> .SRCINFO
          echo "	makedepends = jq" >> .SRCINFO
          echo "	depends = fuse2" >> .SRCINFO
          echo "	depends = hicolor-icon-theme" >> .SRCINFO
          echo "	depends = gtk-update-icon-cache" >> .SRCINFO
          echo "	depends = desktop-file-utils" >> .SRCINFO
          echo "	provides = nerimity" >> .SRCINFO
          echo "	conflicts = nerimity" >> .SRCINFO
          echo "	options = !strip" >> .SRCINFO
          echo "" >> .SRCINFO
          echo "pkgname = nerimity-appimage" >> .SRCINFO
          
          # Commit changes to GitHub (github branch)
          git add PKGBUILD .SRCINFO
          git commit -m "Update to version ${{ steps.check-updates.outputs.latest_version }}"
          git push origin github

      - name: Update aur branch for AUR
        if: steps.check-updates.outputs.update_needed == 'true'
        run: |
          # Create a temporary branch from aur
          git fetch origin aur
          git checkout -b temp-aur origin/aur
          
          # Copy updated files to aur branch
          cp PKGBUILD .SRCINFO nerimity-appimage.install update_srcinfo.sh README.md temp-aur/
          
          # Commit and push to aur
          cd temp-aur
          git add .
          git commit -m "Update to version ${{ steps.check-updates.outputs.latest_version }}"
          git push origin HEAD:aur

      - name: Clone AUR repository
        if: steps.check-updates.outputs.update_needed == 'true'
        run: |
          # Clone AUR repository to a temporary directory
          git clone ssh://aur@aur.archlinux.org/nerimity-appimage.git aur-repo
          
          # Copy updated files to AUR repository
          cp PKGBUILD .SRCINFO nerimity-appimage.install update_srcinfo.sh README.md aur-repo/
          
          # Commit and push to AUR
          cd aur-repo
          git add .
          git commit -m "Update to version ${{ steps.check-updates.outputs.latest_version }}"
          git push